
# https://aka.ms/yaml

pr:
  autoCancel: true

trigger:
  - main

pool:
  vmImage: ubuntu-latest


stages:
  - stage: validate
    displayName: "Ensure that the code works"
    jobs:
      - job: audit
        steps:
          - bash: make audit lint
  - stage: releaseCandidate
    displayName: "Build the App"
    jobs:
      - job: releaseCandidate
        steps:
          - bash: make image

    dependsOn: validate
  - stage: testEnv
    displayName: "Deploy to Test Environment"
    dependsOn: releaseCandidate
    jobs:
      - job: testEnv
        steps:
          - bash: testEnv

      - job: dastScanTest
        steps:
          - bash: "dast.sh test"

  - stage: prodEnv
    displayName: "Deploy to Production Environment"
    dependsOn: testEnv
    jobs:
      - job: prodEnv
        steps:
          - bash: make prodEnv


      - job: dastScanTest
        steps:
          - bash: "dast.sh production"
  
