
# https://aka.ms/yaml

pr:
  autoCancel: true

trigger:
  - main

pool:
  vmImage: ubuntu-latest


stages:
  - stage: validate
    displayName: "Ensure that the code works"
    jobs:
      - job: audit
        steps:
          - bash: make audit lint

  - stage: releaseCandidate
    displayName: "Build the App"
    jobs:
      - job: "dockerBuild"
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'Playpen ACR'
            repository: 'playpen'
            command: 'buildAndPush'
            Dockerfile: 'Dockerfile'
            buildContext: '.'
            tags: |
              latest
              $(Build.BuildId)
  

    dependsOn: validate
  - stage: testEnv
    displayName: "Deploy to Test Environment"
    dependsOn: releaseCandidate
    jobs:
      - deployment: testEnv
        displayName: do the deploy to test
        environment: "Test Environment"
        strategy:
          runOnce:
            deploy:
              steps:
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'Azure RM (TF)'
                  appType: 'webAppContainer'
                  WebAppName: 'test-builddoctor-pipeline-playpen'
                  DockerNamespace: 'builddoctorplaypen.azurecr.io'
                  DockerRepository: 'playpen'
                  DockerImageTag: '$(Build.BuildId)'
                

      - job: dastScanTest
        dependsOn: testEnv
        steps:
          - task: Bash@03
            inputs:
              filePath: 'dash.sh'
              arguments: 'test'
              failOnStderr: false
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'zap.xml'

  - stage: prodEnv
    displayName: "Deploy to Production Environment"
    dependsOn: testEnv
    jobs:
      - job: prodEnv
        steps:
          - bash: make prodEnv



      - job: dastScanTest
        steps:
          - bash: "dast.sh production"
  
