# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  autoCancel: true

trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
  - stage: validate
    displayName: "Ensure that the code works"
    jobs:
      - job: audit
        steps:
          - task: CMake@1
            inputs:
              cmakeArgs: audit lint
  - stage: releaseCandidate
    displayName: "Build the App"
    jobs:
      - job: releaseCandidate
        steps:
          - task: CMake@1
            inputs:
              cmakeArgs: image
    dependsOn: validate
  - stage: testEnv
    displayName: "Deploy to Test Environment"
    dependsOn: releaseCandidate
    jobs:
      - job: testEnv
        steps:
          - task: CMake@1
            inputs:
              cmakeArgs: testEnv

  - stage: prodEnv
    displayName: "Deploy to Production Environment"
    dependsOn: testEnv
    jobs:
      - job: prodEnv
        steps:
          - task: CMake@1
            inputs:
              cmakeArgs: prodEnv
  
